export const ProfileAction = {
  PROFILE_S: "PROFILE_S",
  PROFILE_R: "PROFILE_R",
  HEALTH_POINT_S: "HEALTH_POINT_S",
  HEALTH_POINT_R: "HEALTH_POINT_R",
  PDPA_R: "PDPA_R",
  Q_SURVAY_R: "Q_SURVAY_R",
  SETTOKEN_R: "SETTOKEN_R",
  SETTOKEN_S: "SETTOKEN_S",
};
