export const MasterAction = {
  IS_MODAL_OPEN: "IS_MODAL_OPEN",
  FETCH_ACTIVITIES_LST_R: "FETCH_ACTIVITIES_LST_R",
  FETCH_ACTIVITIES_LST_S: "FETCH_ACTIVITIES_LST_S",
  FETCH_COMMUNITIES_LST_R: "FETCH_COMMUNITIES_LST_R",
  FETCH_COMMUNITIES_LST_S: "FETCH_COMMUNITIES_LST_S",
};
